name: WarGear
version: ${project.build.version}
api-version: 1.20
description: Postremus Wargear Fight Plugin
website: http://dev.bukkit.org/bukkit-plugins/wargear-fight/
author: postremus
main: de.pro_crafting.wg.WarGear
depend: [WorldEdit]
soft-depend: [Vault, AdminCmd, Essentials, CommandBook]
